#!/bin/bash
# =============================================================================
# semelpass-oss — setup.sh
# Interactive environment generator
# Run once: bash setup.sh
# =============================================================================

set -e

RED='[0;31m'
GRN='[0;32m'
YLW='[1;33m'
BLD='[1m'
RST='[0m'

echo ""
echo -e "${BLD}semelpass-oss — Setup${RST}"
echo -e "Solid. Secure. Sovereign."
echo "============================================"
echo ""

# ── Check dependencies ────────────────────────────────────────────────────────
for cmd in docker python3 openssl; do
    if ! command -v $cmd &>/dev/null; then
        echo -e "${RED}ERROR: $cmd is required but not installed.${RST}"
        exit 1
    fi
done
echo -e "${GRN}✓ Dependencies OK${RST}"
echo ""

# ── Guard: don't overwrite existing .env ──────────────────────────────────────
if [ -f .env ]; then
    echo -e "${YLW}WARNING: .env already exists.${RST}"
    read -p "Overwrite it? (y/N): " confirm
    [[ "$confirm" =~ ^[Yy]$ ]] || { echo "Aborted."; exit 0; }
fi

echo -e "${BLD}Answer the prompts below. Press Enter to accept defaults.${RST}"
echo ""

# ── Domain ────────────────────────────────────────────────────────────────────
echo -e "${BLD}[1/7] Domain${RST}"
read -p "Your public domain (e.g. auth.yourcompany.com): " BASE_URL
BASE_URL="${BASE_URL:-http://localhost:8000}"
[[ "$BASE_URL" != http* ]] && BASE_URL="https://$BASE_URL"
ALLOWED_ORIGINS="$BASE_URL"
echo -e "${GRN}✓ BASE_URL=$BASE_URL${RST}"
echo ""

# ── Database ──────────────────────────────────────────────────────────────────
echo -e "${BLD}[2/7] Database${RST}"
read -p "Postgres DB name [semelpass]: " POSTGRES_DB
POSTGRES_DB="${POSTGRES_DB:-semelpass}"
read -p "Postgres user [semelpass]: " POSTGRES_USER
POSTGRES_USER="${POSTGRES_USER:-semelpass}"
POSTGRES_PASSWORD=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
echo -e "${GRN}✓ Postgres password generated${RST}"
echo ""

# ── Redis ─────────────────────────────────────────────────────────────────────
echo -e "${BLD}[3/7] Redis${RST}"
REDIS_PASSWORD=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
echo -e "${GRN}✓ Redis password generated${RST}"
echo ""

# ── Secrets ───────────────────────────────────────────────────────────────────
echo -e "${BLD}[4/7] Cryptographic secrets (auto-generated)${RST}"
JWT_SECRET=$(python3 -c "import secrets; print(secrets.token_hex(32))")
HMAC_SECRET=$(python3 -c "import secrets; print(secrets.token_hex(32))")
FERNET_KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" 2>/dev/null || openssl rand -base64 32)
echo -e "${GRN}✓ JWT secret generated${RST}"
echo -e "${GRN}✓ HMAC secret generated${RST}"
echo -e "${GRN}✓ Fernet key generated${RST}"
echo ""

# ── Mail ──────────────────────────────────────────────────────────────────────
echo -e "${BLD}[5/7] Mail${RST}"
read -p "From email [welcome@$( echo $BASE_URL | sed 's|https://||;s|http://||' )]: " MAIL_FROM
MAIL_FROM="${MAIL_FROM:-welcome@semelpass.com}"
MAIL_FROM_NAME="semelpass"
echo -e "${GRN}✓ Mail configured${RST}"
echo ""

# ── Admin ─────────────────────────────────────────────────────────────────────
echo -e "${BLD}[6/7] Admin${RST}"
read -p "Admin email address: " ADMIN_EMAIL
echo -e "${GRN}✓ Admin email set${RST}"
echo ""

# ── Stripe (optional) ─────────────────────────────────────────────────────────
echo -e "${BLD}[7/7] Stripe (optional — skip for OSS/free tier)${RST}"
echo -e "Leave blank to skip. Add later by editing .env"
read -p "Stripe secret key (sk_live_... or sk_test_...): " STRIPE_SECRET_KEY
read -p "Stripe publishable key (pk_live_... or pk_test_...): " STRIPE_PUBLISHABLE_KEY
read -p "Stripe webhook secret (whsec_...): " STRIPE_WEBHOOK_SECRET
echo ""

# ── Write .env ────────────────────────────────────────────────────────────────
cat > .env << EOF
# semelpass-oss — generated by setup.sh $(date +%Y-%m-%d)
# DO NOT commit this file. See .env.example for reference.

APP_ENV=production
APP_HOST=0.0.0.0
APP_PORT=8000
BASE_URL=${BASE_URL}
APP_VERSION=26.05.1.0
ALLOWED_ORIGINS=${ALLOWED_ORIGINS}

POSTGRES_DB=${POSTGRES_DB}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

REDIS_PASSWORD=${REDIS_PASSWORD}

JWT_SECRET=${JWT_SECRET}
JWT_ALGORITHM=HS256
JWT_ACCESS_EXPIRE_MINUTES=15
JWT_REFRESH_EXPIRE_DAYS=7

FERNET_KEY=${FERNET_KEY}
HMAC_SECRET=${HMAC_SECRET}

MAIL_FROM=${MAIL_FROM}
MAIL_FROM_NAME=${MAIL_FROM_NAME}
SMTP_HOST=semelpass-postfix
SMTP_PORT=25

OTP_LENGTH=6
OTP_EXPIRE_MINUTES=10
OTP_MAX_ATTEMPTS=5
MAGIC_LINK_EXPIRE_MINUTES=15

RATE_BUCKET_CAPACITY=10
RATE_REFILL_SECONDS=20

ADMIN_EMAIL=${ADMIN_EMAIL}

JUICE_DEMO_EMAIL=admin@juice-sh.op
JUICE_DEMO_PASSWORD=admin123

STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
STRIPE_SEMELPASS_PRODUCT_ID=
STRIPE_PRICE_SELF_HOSTED_MONTHLY=
STRIPE_PRICE_SELF_HOSTED_ANNUAL=
STRIPE_PRICE_SELF_HOSTED_2YEAR=
STRIPE_PRICE_SELF_HOSTED_3YEAR=
STRIPE_PRICE_MANAGED_MONTHLY=
STRIPE_PRICE_MANAGED_ANNUAL=
STRIPE_PRICE_MANAGED_2YEAR=
STRIPE_PRICE_MANAGED_3YEAR=
EOF

chmod 600 .env
echo -e "${GRN}${BLD}✓ .env written and locked (chmod 600)${RST}"
echo ""

# ── Done ──────────────────────────────────────────────────────────────────────
echo "============================================"
echo -e "${BLD}Setup complete.${RST}"
echo ""
echo "Next steps:"
echo "  1. Review .env — verify BASE_URL and ADMIN_EMAIL"
echo "  2. docker compose up -d"
echo "  3. Visit your domain"
echo ""
echo -e "Questions? ${RED}welcome@semelpass.com${RST}"
echo ""
